### PR TITLE
Optionally retry on IN_PROGRESS status

### LINKED ISSUE #91: uploadState: 'IN_PROGRESS' not handled and failing upload
Hi! We've been using this CLI for a year now without issue. Recently in the past few weeks, the CLI has been failing on the upload step when running from our CI (Github Actions) with the following error:

### Version
`3.3.2` (`6c3ac3551ece62339b92b717a350416c4af23c9c`)

### Command
```bash
# This fails with and without the --auto-publish flag, with the same result
chrome-webstore-upload upload --source {path} --auto-publish
```

### Error
```
- Uploading chrome-extension-06f49bfa86f1c90c0e1eacaf769683a19d38a7d7.zip
{
  kind: 'chromewebstore#item',
Error: IN_PROGRESS
Processing
  id: 'foilfbjokdonehdajefeadkclfpmhdga',
  uploadState: 'IN_PROGRESS',
  itemError: [ { error_code: 'IN_PROGRESS', error_detail: 'Processing' } ]
}
```

Looking at the error + code it seems like there's no handling for in progress/processing builds. Not sure if this is new / what would have caused this new status, but we aren't aware of any recent build changes on our end that would have prompted this.

Is there something we can do to get around this status easily, or can handling for this be added to the CLI? Ideally there would be some backoff and rechecking of the status to automatically wait for the processing status to resolve!

Happy to provide any more details as needed!

### PR DESCRIPTION
**Pull request by andyghiuta**
- fixes #91

### CODE REVIEW

**Comment by fregante** [comment]
You're not wrong, but it still provides helpers around it, like optional retries

**Comment by fregante** [comment]
By the way the retries naming and logic needs to be specific to IN_PROGRESS. Currently this PR exposes it as a generic "uploadRetries", which might suggest that it will also retry network failures for example. I don't want to implement that at this point.

**Comment by andyghiuta** [comment]
Sorry for the delay here. I was under the impression that you'll take over. Please see the last changes

File: config.js [hunk 1]
```diff
@@ -17,5 +17,6 @@ export default async function getConfig(command, flags) {
         autoPublish: flags.autoPublish || !command,
         trustedTesters: flags.trustedTesters,
         deployPercentage: flags.deployPercentage,
+        maxAwaitInProgress: flags.maxAwaitInProgress || process.env.MAX_AWAIT_IN_PROGRESS || undefined,
```
Comment (fregante) [inline config.js:20]:
```suggestion
        maxAwaitInProgress: flags.maxAwaitInProgress
```

ENVs are only used for secrets, no need for fallbacks

File: cli.js [hunk 2]
```diff
@@ -155,6 +153,8 @@ function errorHandler(error) {
             console.error('Error: ' + itemError.error_code);
             console.error(itemError.error_detail);
         }
+    } else {
+        console.error('Error: ' + (error?.message || 'Unknown error'));
```
Comment (fregante) [inline cli.js:157]: What is this for? The first line of the function already outputs the full error, the extra conditions are to *add* information. Should be reverted

**Review by fregante — APPROVED** [review]
Looks good! Have you had the chance to test it? I'll publish it as a beta shortly so you can try it in production before merging

**Comment by andyghiuta** [comment]
Initial test failed. It waited for a bit, but not sufficient. I think it's due to the flag being seen as string? I've updated the type. Let me know when you have another build up

**Comment by andyghiuta** [comment]
nvm, I see what I did, fixing.

**Comment by andyghiuta** [comment]
So far it's behaving well. No issues in the Github actions

**Comment by andyghiuta** [comment]
@fregante I think this is good to merge. I had a few releases with no issues.
